# Generated by Django 6.0.4 on 2026-05-08 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_customerprofile_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_api.merchant'),
        ),
    ]
