# Generated by Django 6.0.4 on 2026-05-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_alter_transaction_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('CASH', 'Cash')], default='ONLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/proofs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('MERCHANT', 'Merchant'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
