# Generated by Django 6.0.4 on 2026-05-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_state_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='referral_earnings',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MERCHANT', 'Merchant'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
